version: '3.7'

services:
  makepdfs:
    container_name: googledrive
    build:
      context: .
      dockerfile: Dockerfile
    image: "docker.pkg.github.com/mkrakowitzer/actions-googledrive/googledrive:${TAG:-latest}"
